server:
  port: 8083
spring:
  data:
    mongodb:
      database: demo
      uri: mongodb+srv://paginas:paginas@paginas-o5dde.mongodb.net/test?retryWrites=true&w=majority

#ribbon:
#  MaxAutoRetries: 1
#  MaxAutoRetriesNextServer: 1
#  eureka:
#    enabled: false
#
#change:
#  ribbon:
#    ServerListRefreshInterval: 2000
#    listOfServers: consulta-peru-demo.herokuapp.com,localhost:5000